### ISSUE TITLE
关于下载时遇到的问题咨询

### ISSUE THREAD

**Issue by hwm-jmz** [tyokyo320/bilibili-downloader#1]
![image](https://user-images.githubusercontent.com/79967015/124339651-7e1f3b80-dbe2-11eb-962c-51094e347af4.png)

您好，我已经配置好了环境，上图所示，并且也更新了SESSDATA，下载时遇到了问题，下图，请问方便教我一下吗？

![image](https://user-images.githubusercontent.com/79967015/124339707-dbb38800-dbe2-11eb-9b63-f04710708f8a.png)

**Comment by aaron9610** [comment]
您好，感谢您的提问。非常抱歉，目前暂未更新至可支持下载番剧和纪录片。

如果其他类型视频下载出现问题，欢迎您的提问，谢谢。
