### ISSUE TITLE
4K视频下载

### ISSUE THREAD

**Issue by yilingqinghan** [tyokyo320/bilibili-downloader#23]
请问下支持4K吗？
log:17分钟带你沉浸式体验攀登珠峰，这也是人类历史上第一次有人拍摄完整的珠峰路线，4K高清
下载的视频清晰度：清晰 480P

为什么这里只有480P（我有大会员的）

**Comment by aaron9610** [comment]
@yilingqinghan ,

你好，感谢你的提问
这个是因为你没有定期更换 COOKIE 的值，所以会变成试看模式的 480p

刚刚我试了一下是可以获取更高清晰度的，请参照 README 更换一下 `config.py` 文件中的 COOKIE 再试一下

**Comment by yilingqinghan** [comment]
感谢！
