### ISSUE TITLE
视频合成太慢

### ISSUE THREAD

**Issue by BarryZou** [tyokyo320/bilibili-downloader#6]
如题，感觉moviepy在用ffmpeg重新编码视频，不是应该直接合成吗

**Comment by aaron9610** [comment]
> 

谢谢回复。如你所说，的确合成的时候花费时间较长，后续有时间会再优化一下。

**Comment by wzh1895** [comment]
ffmpeg有非常快速的合并选项*，如果有办法定位ffmpeg的可执行文件，或许可以用subprocess.run()直接执行bash或cmd命令调用ffmpeg。

*供参考：https://superuser.com/questions/277642/how-to-merge-audio-and-video-file-in-ffmpeg
