### ISSUE TITLE
请问非会员也可以下载4K视频嘛？

### ISSUE THREAD

**Issue by Alroy261** [tyokyo320/bilibili-downloader#7]
如题。如果可以的话就clone到自己电脑上试一下。谢谢开发团队！

**Comment by aaron9610** [comment]
> 如题。如果可以的话就clone到自己电脑上试一下。谢谢开发团队！

非常抱歉说明引起误解，这里是需要大会员才能下载 4K 的视频。因为需要用到 `COOKIE`，可以复制其他人的大会员 `COOKIE`使用！
